### ISSUE TITLE
Question: starting countdown from input

### ISSUE THREAD

**Issue by hyukishi** [ontje/node-red-contrib-countdown#1]
Is it possible to start the countdown upon the injection of the "number" payload from a previous function?

As it stands, I have to use another node to start the countdown after setting it with the number provided by the function I'm using.

If so, could you please provide an example?

Thank you in advance!

**Comment by ontje** [comment]
Jey hyukishi,

it was not possible, but quite easy to implement - so I did. I just published v1.1.0, if you update the node configuration will have a new checkbox: "Start countdown if control message is recieved while not running" which is uncheckt by default. If you check it, the node should show the behaviour you asked for.

Please note: It will take some time until node-red picks up the updated package, so before you try to update, look here if it reads v.1.1.0 already. 
https://flows.nodered.org/node/node-red-contrib-countdown

**Comment by hyukishi** [comment]
I should also mention that I did not see the new checkbox verbatim. I assumed it had taken the place of the former with similar verbiage.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/11379349/81857922-8d4bb180-9528-11ea-81ca-6de34affbaa8.png">

**Comment by hyukishi** [comment]
I've deleted my 2 previous comments as they are no longer relevant. I must've had something going on with my web cache at the time. All is well now and the function is working as expected.

Thank you for implementing my request! Cheers!

**Comment by ontje** [comment]
Glad it works!
