### ISSUE TITLE
Timer on/off payload

### ISSUE THREAD

**Issue by wpirkl** [ontje/node-red-contrib-countdown#4]
When setting the timer on/off payload to msg.payload, the countdown node sends out {"payload": "payload"} instead of the payload from the incoming message.
This does not depend on the topic.

**Comment by marc-gist** [comment]
Agreed, it appears that this node does not keep anything from the previous node, but creates a totally new payload.
It would be great if this node kept the previous nodes payloads, and only overrides if set to in config.

**Comment by marc-gist** [comment]
I've fixed in my fork: https://github.com/marc-gist/node-red-contrib-countdown

**Comment by ontje** [comment]
I have incooperated marc-gist fix to this issue with the current version. Thanks Marc!
