### ISSUE TITLE
Inconsistent documents.

### ISSUE THREAD

**Issue by Just-another-pleb** [ontje/node-red-contrib-countdown#8]
>  Also the countdown timer can be set to any new countdown value at any time to reload the timer with a specific value.

How?

Not explained in the documents that I can see.

**Comment by StephanStS** [comment]
See example "Reloading the countdown timer". This reloads the timer register to an arbitrary value during the timer runs.

**Comment by Just-another-pleb** [comment]
You need to edit that example.

`inject 6` is not what it is doing.

**Comment by StephanStS** [comment]
@Just-another-pleb: Thanks for the feedback. Corrected with pull request #9.

**Comment by StephanStS** [comment]
Also see section "Input" in the README.md for an explanation.

**Comment by Just-another-pleb** [comment]
I think I have now got what I want working.

**Comment by Just-another-pleb** [comment]
Ok, I goofed.   It is now closed.
